# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tal and Neela
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
